name: buildDeb

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - '*' # This doesn't mean that it HAS to have a tag, only that the workflow triggers when we push a tag

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-24-04:
    runs-on: ubuntu-24.04

    steps:
      - name: build
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libqrencode-dev libpng-dev build-essential gcc g++ pkg-config make debhelper devscripts
          mkdir root
          curl -L --output linux-wifi-hotspot.tar.gz --silent https://github.com/lakinduakash/linux-wifi-hotspot/archive/refs/tags/v4.7.1.tar.gz
          tar -xzf linux-wifi-hotspot.tar.gz
          cd linux-wifi-hotspot-4.7.1
          debuild -uc -us

      - name: upload
        uses: softprops/action-gh-release@v2
        with:
          files: linux-wifi-hotspot_4.7.1_amd64.deb
  
